import type { Metadata } from "next";
import localFont from "next/font/local";
import { Roboto } from "next/font/google";

import "./globals.css";
import { CSPostHogProvider } from "./providers";

const varsity = localFont({
  src: "../public/VarsityTeam-Bold.otf",
});

const roboto = Roboto({
  weight: "700",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <CSPostHogProvider>
        <body className={`${varsity.className} ${roboto.className}`}>
          {children}
        </body>
      </CSPostHogProvider>
    </html>
  );
}
